### ISSUE TITLE
Generate a ggplot object from view_palette() instead of a base R plot

### ISSUE THREAD

**Issue by charliejhadley** [cararthompson/monochromeR#1]
`view_palette()` currently uses `scales::show_col()` to generate a visual representation of a chart, which uses `plot()` to generate base R plot.

It would be convenient if `view_palette()` generated a `ggplot` object so that it could be passed into `colorblindr::cvd_grid()` to check how a palette appears for folks with colour blindness.

**Comment by cararthompson** [comment]
Thanks for this @charliejhadley. That sounds like it would be a good improvement. I don't have time to look at it just now but feel free to give it a go! More than happy to collaborate on this.

**Comment by cararthompson** [comment]
Would something like this do the trick? Adding text in black and white so we can check contrast. Is there anything else you'd find helpful?

![image](https://user-images.githubusercontent.com/14091282/191839593-d669b925-1579-4d37-a107-f5e85f35b81d.png)

**Comment by charliejhadley** [comment]
This looks pretty awesome - thank you!!

**Comment by cararthompson** [comment]
I've just pushed the updated code. Thanks for the suggestion!
