### ISSUE TITLE
Small Typo in "How can I use it?" Section

### ISSUE THREAD

**Issue by kpivert** [cararthompson/monochromeR#2]
Hi Cara, 
This a great package. Looking forward to learning more about it in your Workshop for Ukraine today. Just wanted to let you know that there was a small typo in the _How can I use it?_ section. 

Instead of `remotes::github_install("cararthompson/monochromeR")` it should be `remotes::install_github("cararthompson/monochromeR")`.

Thanks,
Kurtis

**Comment by cararthompson** [comment]
Thanks for the bug report, @kpivert ! Fixed it now.
